display.html.gift.giftListItem=Gift Card
display.html.gift.removeGiftListItem=Remove
display.html.gift.balance=Balance:
display.html.gift.checkBalance=Check Balance
display.html.gift.apply=Apply

display.html.fastlane.edit=Change card

display.html.token.guest.default=Guest Card

display.ach.legal.accept=I agree with the above statement
display.ach.confirmFields=Confirm