display.html.gift.giftListItem=Gift Card
display.html.gift.removeGiftListItem=Remove
display.html.gift.balance=Balance:
display.html.gift.checkBalance=Check Balance
display.html.gift.apply=Apply

display.html.fastlane.edit=Change card

display.html.token.guest.default=Guest Card

display.uma.legal.accept=上記の誓いに同意します - スペシャルウィーク！
display.uma.confirmFields=ウマ娘GO！