# Default SCM CI Template for All commerceHub Applications
include:
  - project: 'na/gbs/carat-digital-ecommerce/commercehub/SRE/gitlab-ci'
    ref: MCH-24518
    file: '/template-salesforce.yml'
variables:
  ARTIFACT_TYPE : "React"
  APM_ID: "0011801"